### ISSUE TITLE
suggestion by mr spiky santa himself

### ISSUE THREAD

**Issue by SpikySanta123** [gooderprojects/gooderprojects.github.io#26]
Suggest timer here.
if you can you should do a timer until good old spiky santa comes and gives little children candy on his cart with flying horses 
(AKA christmas)

**Comment by Zbomb2000** [comment]
At the beginning of the school year there is a Christmas break timer. I'll add it back next school year.

**Comment by SpikySanta123** [comment]
> 

ok
