### ISSUE TITLE
wordle suggestions

### ISSUE THREAD

**Issue by SpikySanta123** [gooderprojects/gooderprojects.github.io#27]
Type suggestion here...
weddle, poeltl, and WARdle

**Comment by SpikySanta123** [comment]
also known as nfl wordle, nba wordle, and mlb wordle

**Comment by Zbomb2000** [comment]
Ok, I'll start working on it tomorrow.

**Comment by SpikySanta123** [comment]
ayyyyy

**Comment by Zbomb2000** [comment]
Now I'm actually going to start working on it.

**Comment by Zbomb2000** [comment]
Done.
